language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
addons:
  postgresql: "9.4"
before_install:
- gem install bundler 
dist: trusty
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rspec
- sbt clean coverage test coverageReport && sbt coverageAggregate
after success:
- sbt coveralls
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  app: innercise
  on:
    repo: Kittaru87/innercise
  run:
  - bundle exec rails db:migrate
  - bundle exec rails db:seed
  api_key:
    secure: Xhte7NyAJ/QwP4PFwspttM705jQBcNmFkutI9rLRF4K3eCTPON4NBc5JGEVCc2Btyhb2PCsGa/YOah9m4HZfklZU5bYnhmT7MeXBypI6bhhnDBewGExs0WUt4gN9mQuZyJhcdseHHEos1RdbLsnCRlR0kZCSdWpmA7XoOeRz8qJRy0KEJlZiT744fjIrr+yFxSg+jWiDN0pZw0UDvcgDc5gt13qS3wa3wkcYSwcjq5K/ujs29LGdpvgk4uGiYwzFJQYoiEfPI3nBR7IC2/4kmGhI0giVWr5wahxNQhRdsSibj88HE1oXtOy8kGWEly32CjYQCos1XFHo33Pn5bUCJuVT34SUE1oPYEtYZuPRgZJJ480YyM11tBS2H1byemUXIjfjDBwW9CZEs8rredhh4zuXAXU+qsLEmnAQOGylUTnpzRND4fgnCHGTzjZ+Pvxmxnv97KwK8sCqUM8Gsbitn6vDNAXRM7o85XN/7XjYgS7/npeia3N8/NnPPR+RncVIpVeMDcAParyurN0QVaNzeA8IRW2QIuNZKIsRN9Ufij4UdB0N7/Uuj/edoDyMf8ZweaGflfwN569qchfKRQq/xbAv7yR1wq4p8nmpxoI0PRM97BozLDz46mIw21McPbad0YileYwc1JBWH1zUUflMSIc4SmXPXdBU69Y32asqfWA=